from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from app.models.item import Item
from app.models.refresh_token import RefreshToken
from app.models.request_log import RequestLog
from app.models.role import Permission, Role
from app.models.user import User
from app.models.user_preferences import UserPreferences
from app.schemas.request_log import RequestLogQuery


class UserRepositoryProtocol(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...

    async def get(self, user_id: int) -> User | None: ...

    async def create(self, user: User) -> User: ...

    async def save(self, user: User) -> User: ...

    async def list_all(self, limit: int, offset: int) -> Sequence[User]: ...

    async def count_all(self) -> int: ...

    async def count_for_role(self, role_id: int) -> int: ...

    async def exists_any(self) -> bool: ...

    async def soft_delete(self, user: User) -> None: ...


class RoleRepositoryProtocol(Protocol):
    async def get(self, role_id: int) -> Role | None: ...

    async def get_by_name(self, name: str) -> Role | None: ...

    async def list_all(self) -> Sequence[Role]: ...

    async def create(self, role: Role) -> Role: ...

    async def save(self, role: Role) -> Role: ...

    async def delete(self, role: Role) -> None: ...


class PermissionRepositoryProtocol(Protocol):
    async def get(self, resource: str, action: str) -> Permission | None: ...

    async def list_all(self) -> Sequence[Permission]: ...


class ItemRepositoryProtocol(Protocol):
    async def list_for_owner(
        self, owner_id: int, limit: int, offset: int
    ) -> Sequence[Item]: ...

    async def count_for_owner(self, owner_id: int) -> int: ...

    async def get_for_owner(self, item_id: int, owner_id: int) -> Item | None: ...

    async def create(self, item: Item) -> Item: ...

    async def save(self, item: Item) -> Item: ...

    async def soft_delete(self, item: Item) -> None: ...

    async def soft_delete_for_owner(self, owner_id: int) -> None: ...


class RequestLogRepositoryProtocol(Protocol):
    async def create(self, entry: RequestLog) -> RequestLog: ...

    async def list_page(self, query: RequestLogQuery) -> Sequence[RequestLog]: ...

    async def delete_batch_created_before(
        self, cutoff: datetime, batch_size: int
    ) -> int: ...


class PreferencesRepositoryProtocol(Protocol):
    async def get_for_user(self, user_id: int) -> UserPreferences | None: ...

    async def create(self, preferences: UserPreferences) -> UserPreferences: ...

    async def save(self, preferences: UserPreferences) -> UserPreferences: ...


class RefreshTokenRepositoryProtocol(Protocol):
    async def create(self, token: RefreshToken) -> RefreshToken: ...

    async def get_active(
        self, token_hash: str, now: datetime
    ) -> RefreshToken | None: ...

    async def revoke(self, token_hash: str, now: datetime) -> int: ...

    async def revoke_all_for_user(self, user_id: int, now: datetime) -> int: ...

    async def delete_expired(self, now: datetime) -> int: ...
