"""add single use account tokens

Revision ID: 4e9943672be8
Revises: 5edda92271a7
Create Date: 2026-09-12 19:19:25.827052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9943672be8'
down_revision: Union[str, Sequence[str], None] = '5edda92271a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_use_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_single_use_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_single_use_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_single_use_tokens_token_hash'))
    )
    op.create_index(op.f('ix_single_use_tokens_user_id'), 'single_use_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_index(op.f('ix_single_use_tokens_user_id'), table_name='single_use_tokens')
    op.drop_table('single_use_tokens')
    # ### end Alembic commands ###
