"""add indexes and cascade deletes

Revision ID: a5f508821053
Revises: d43209d5e476
Create Date: 2026-09-22 14:17:30.208731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f508821053'
down_revision: Union[str, Sequence[str], None] = 'd43209d5e476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_attachments_item_id_items'), 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attachments_item_id_items'), 'attachments', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.create_index('ix_items_owner_id_deleted_at', 'items', ['owner_id', 'deleted_at'], unique=False)
    op.drop_constraint(op.f('fk_items_owner_id_users'), 'items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_owner_id_users'), 'items', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('request_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.execute("ALTER SEQUENCE request_logs_id_seq AS bigint")
    op.drop_constraint(op.f('fk_single_use_tokens_user_id_users'), 'single_use_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_single_use_tokens_user_id_users'), 'single_use_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_preferences_user_id_users'), 'user_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_preferences_user_id_users'), 'user_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_preferences_user_id_users'), 'user_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_preferences_user_id_users'), 'user_preferences', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_single_use_tokens_user_id_users'), 'single_use_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_single_use_tokens_user_id_users'), 'single_use_tokens', 'users', ['user_id'], ['id'])
    op.execute("ALTER SEQUENCE request_logs_id_seq AS integer")
    op.alter_column('request_logs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_items_owner_id_users'), 'items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_owner_id_users'), 'items', 'users', ['owner_id'], ['id'])
    op.drop_index('ix_items_owner_id_deleted_at', table_name='items')
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.drop_constraint(op.f('fk_attachments_item_id_items'), 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attachments_item_id_items'), 'attachments', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
